[build]
command = "npm install && npm run build:cloudflare"

[site]
bucket = ".vercel/output/static"

[build.environment]
NODE_VERSION = "18"

[pages]
pages_build_output_dir = ".vercel/output/static" 